### ISSUE TITLE
npx iconfont-init 在win10下 无法运行 报错

### ISSUE THREAD

**Issue by jiangz153202** [iconfont-cli/mini-program-iconfont-cli#4]
PS D:\gxjzFolder\painterDemo\painter> npx iconfont-init
npx: 1 安装成功，用时 5.933 秒
'prefix' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
D:\gxjzFolder\painterDemo\painter\node_modules\mini-program-iconfont-cli\commands\createJson.js:13
    fs_1.default.copyFileSync(path_1.default.join(__dirname, '../libs/iconfont.json'), targetFile);
                 ^

TypeError: fs_1.default.copyFileSync is not a function
    at Object.<anonymous> (D:\gxjzFolder\painterDemo\painter\node_modules\mini-program-iconfont-cli\commands\createJson.js:13:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

node版本 V8.4.0

**Comment by fwh1990** [comment]
`fs.copyFileSync` 是nodeJs `v8.5.0`之后的功能，我找下代替方案

**Comment by jiangz153202** [comment]
> `fs.copyFileSync` 是nodeJs `v8.5.0`之后的功能，我找下代替方案

非常感谢 因为在做公司项目 准备上线中 不太想因为升级node环境而搞出幺蛾子 ==

**Comment by fwh1990** [comment]
已经发布`0.5.5`版本。

**Comment by jiangz153202** [comment]
> 已经发布`0.5.5`版本。

非常感谢 =
